@startuml
hide footbox
title 时序图
== 鉴权阶段 ==
张三 -> 李四: 请求
李四 -> 张三: 应答

== 数据上传 ==
张三 -> 李四: 上传数据
note left: 这是显示在左边的备注
李四 --> 王五: 转交数据
... 不超过 5 秒钟 ...
王五 --> 李四: 状态返回
note right: 这是显示在右边的备注
李四 -> 张三: 状态返回

== 状态显示 ==
张三 -> 张三: 给自己发消息
张三 -> 王的五: 远程调用
王的五 --> 张三:应答
王五 -> 王的五:请求
@enduml