@startuml
Class Client{
    public String name
    +void  assemble()
}
Interface Set{
+void execute()
}
Class B{
}
Set<|.. Client:实现
B<|--Client
Human *-- Brain
Company o-- Human
Human --> Water:关联
Human ..> Cigarette:依赖

namespace net #DDDD2D {
    .BaseClass <|-- Person
    Meeting o-- Person
    .BaseClass <|- Meeting
}
client <|--net.Person:泛化
@enduml